name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_tests:
    uses: tataranovich/ai-dial-ci/.github/workflows/node_pr.yml@gh-e2e-test
    secrets: inherit
    with:
      node-version: 22
