name: Release Workflow

on:
  push:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: tataranovich/ai-dial-ci/.github/workflows/node_release.yml@gh-e2e-test
    secrets: inherit
    with:
      node-version: 22
      publish-enabled: false
